import 'package:flutter/material.dart';
import 'package:top_examer/ui/matrimony/FullDetailsPage.dart';
import 'package:top_examer/utils/themes.dart';

class MatrimoniePage extends StatelessWidget {
  final SizedBox _verticalSpacing = const SizedBox(height: 5);
  @override
  Widget build(BuildContext buildContext) {
    final colorScheme = Theme.of(buildContext).colorScheme;
    return Scaffold(
      appBar: AppBar(
        backgroundColor: colorScheme.error,
        title: const Text('Matrimony', style: Themes.appBarHeader),
        iconTheme: const IconThemeData(color: Themes.back_arrow),
      ),
      body: ListView(
        //padding: const EdgeInsets.all(10.0),
        children: [
          buildMatrimonieCard(
              buildContext,
              'Mohan Srinivas',
              'A kind-hearted person with a love for nature.',
              'Male',
              '1996-09-12',
              'Software Engineer',
              25,
              'H1B',
              '6304342021',
              'assets/men.jpg',
              '9:55 AM',
              'Guntur',
              'Indian',
              'Hindu',
              'fair',
              'Masters',
              'Sacred heart university',
              'N/A',
              'N/A',
              '37 primrose cir',
              ' Not married',
              'sanjanakoneru25@gmail.com',
              'Kumbha',
              'Cherukunolla',
              'Srinivasa rao koneru',
              'Business',
              1234567890,
              'Usha rani Koneru',
              'Business',
              1234567890,
              'Sravani Koneru',
              1234567890,
              'Hyderabad',
              'Bridegroom',
              'Should be understanding'),
          buildMatrimonieCard(
              buildContext,
              'Jyothirmai Chundru',
              'A passionate artist and traveler to explore the world.',
              'Female',
              '1994-06-26',
              'Graphic Designer',
              29,
              'H1b',
              '1234567890',
              'assets/women2.jpg',
              '9:55 AM',
              'Guntur',
              'Indian',
              'Hindu',
              'fair',
              'Masters',
              'Sacred heart university',
              'N/A',
              'N/A',
              '37 primrose cir',
              ' Not married',
              'sanjanakoneru25@gmail.com',
              'Kumbha',
              'Cherukunolla',
              'Srinivasa rao koneru',
              'Business',
              1234567890,
              'Usha rani Koneru',
              'Business',
              1234567890,
              'Sravani Koneru',
              1234567890,
              'Hyderabad',
              'Bridegroom',
              'Should be understanding'),
          buildMatrimonieCard(
              buildContext,
              'SANJANA KONERU',
              'A passionate artist and traveler to explore the world.',
              'Female',
              '1999-07-25',
              'Graphic Designer',
              25,
              'F1(Stem Opt)',
              '1234567890',
              'assets/women.jpg',
              '9:55 AM',
              'Guntur',
              'Indian',
              'Hindu',
              'fair',
              'Masters',
              'Sacred heart university',
              'N/A',
              'N/A',
              '37 primrose cir',
              ' Not married',
              'sanjanakoneru25@gmail.com',
              'Kumbha',
              'Cherukunolla',
              'Srinivasa rao koneru',
              'Business',
              1234567890,
              'Usha rani Koneru',
              'Business',
              1234567890,
              'Sravani Koneru',
              1234567890,
              'Hyderabad',
              'Bridegroom',
              'Should be understanding'),
        ],
      ),
    );
  }

  Widget buildMatrimonieCard(
    BuildContext context,
    String name,
    String description,
    String gender,
    String DOB,
    String job,
    int age,
    String visa,
    String number,
    String imagePath,
    String TimeofBirth,
    String PlaceofBirth,
    String Nationality,
    String Religion,
    String Color,
    String EducationQualification,
    String Company,
    String Designation,
    String AnnualSalary,
    String USAAddress,
    String MaritalStatus,
    String EmailAddress,
    String Rashinakshatram,
    String Gothram,
    String FatherName,
    String FatherOccupation,
    int FatherContactNumber,
    String MotherName,
    String MotherOccupation,
    int MotherContactNumber,
    String SiblingName,
    int SiblingContactNumber,
    String NativePlaceAddress,
    String LookingFor,
    String PartnerPreferences,
  ) {
    return Padding(
      padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 5),
      child: Card(
        shape: RoundedRectangleBorder(
          borderRadius: BorderRadius.circular(10.0),
        ),
        elevation: 5,
        child: Row(
          children: [
            Padding(
              padding: const EdgeInsets.all(10.0),
              child: CircleAvatar(
                radius: 35,
                backgroundImage: AssetImage(imagePath),
              ),
            ),
            Expanded(
              child: Padding(
                padding: const EdgeInsets.only(left: 10),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text(
                      name,
                      style: const TextStyle(
                        fontSize: 18,
                        fontWeight: FontWeight.w600,
                        fontFamily: Themes.fontFamily,
                      ),
                    ),
                    _verticalSpacing,
                    Text(
                      description,
                      style: const TextStyle(
                          fontSize: 16, fontFamily: Themes.fontFamily),
                    ),
                    _verticalSpacing,
                    Text(
                      '$gender, $age, $visa',
                      style: const TextStyle(
                          fontSize: 14, fontFamily: Themes.fontFamily),
                    ),
                    _verticalSpacing,
                    Text('$DOB',
                        style: const TextStyle(
                            fontSize: 14, fontFamily: Themes.fontFamily)),
                    _verticalSpacing,
                    Text('$number',
                        style: const TextStyle(
                            fontSize: 14, fontFamily: Themes.fontFamily)),
                    Padding(
                      padding: EdgeInsets.only(right: 8, bottom: 8),
                      child: ElevatedButton(
                        style: ButtonStyle(
                          backgroundColor: MaterialStateProperty.all(
                              Theme.of(context).colorScheme.onBackground),
                        ),
                        onPressed: () {
                          Navigator.push(
                            context,
                            MaterialPageRoute(
                              builder: (context) => FullDetailsPage(
                                name: name,
                                description: description,
                                gender: gender,
                                DOB: DOB,
                                job: job,
                                age: age,
                                number: number,
                                visa: visa,
                                imagePath: imagePath,
                                TimeofBirth: TimeofBirth,
                                PlaceofBirth: PlaceofBirth,
                                Nationality: Nationality,
                                Religion: Religion,
                                Color: Color,
                                EducationQualification: EducationQualification,
                                Company: Company,
                                Designation: Designation,
                                AnnualSalary: AnnualSalary,
                                USAAddress: USAAddress,
                                MaritalStatus: MaritalStatus,
                                EmailAddress: EmailAddress,
                                Rashinakshatram: Rashinakshatram,
                                Gothram: Gothram,
                                FatherName: FatherName,
                                FatherOccupation: FatherOccupation,
                                FatherContactNumber: FatherContactNumber,
                                MotherName: MotherName,
                                MotherOccupation: MotherOccupation,
                                MotherContactNumber: MotherContactNumber,
                                SiblingName: SiblingName,
                                SiblingContactNumber: SiblingContactNumber,
                                NativePlaceAddress: NativePlaceAddress,
                                LookingFor: LookingFor,
                                PartnerPreferences: PartnerPreferences,
                              ),
                            ),
                          );
                        },
                        child: Text(
                          'Read Full Details',
                          style: Themes.loginbuttonTextStyle
                              .copyWith(fontSize: 14),
                        ),
                      ),
                    ),
                  ],
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }
}
