// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCscWA0Z9KOJfWqdCMdfMGmrpX8kzp9PGg',
    appId: '1:1038797544250:web:eca61dc6ad36960b068e03',
    messagingSenderId: '1038797544250',
    projectId: 'aira-news-7d139',
    authDomain: 'aira-news-7d139.firebaseapp.com',
    storageBucket: 'aira-news-7d139.appspot.com',
    measurementId: 'G-EKE2KXZ4PG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoggkSr2H2EWRRJ-guXooX3xGWzcgYqBo',
    appId: '1:1038797544250:android:b084df348f0456c5068e03',
    messagingSenderId: '1038797544250',
    projectId: 'aira-news-7d139',
    storageBucket: 'aira-news-7d139.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJ-8BGmbVQfHc6Viie_weLEeQTYFBiF3U',
    appId: '1:1038797544250:ios:c05dc0e7165e2d18068e03',
    messagingSenderId: '1038797544250',
    projectId: 'aira-news-7d139',
    storageBucket: 'aira-news-7d139.appspot.com',
    iosBundleId: 'com.apps.airanews',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJ-8BGmbVQfHc6Viie_weLEeQTYFBiF3U',
    appId: '1:1038797544250:ios:e1bd346886802dc9068e03',
    messagingSenderId: '1038797544250',
    projectId: 'aira-news-7d139',
    storageBucket: 'aira-news-7d139.appspot.com',
    iosBundleId: 'com.apps.topexamer.topExamer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCscWA0Z9KOJfWqdCMdfMGmrpX8kzp9PGg',
    appId: '1:1038797544250:web:e3a3d556ba6e8465068e03',
    messagingSenderId: '1038797544250',
    projectId: 'aira-news-7d139',
    authDomain: 'aira-news-7d139.firebaseapp.com',
    storageBucket: 'aira-news-7d139.appspot.com',
    measurementId: 'G-G3P1MTK660',
  );
}